### PR TITLE
Settings for building on Linux

### PR DESCRIPTION
**Pull request by mikkohei13**
Added settings for building on Linux to readme.
Added missing babel plugin, which prevented the module for building properly.
(Trying out pull requests for managing the commits.)

### CODE REVIEW

**Comment by mskyttner** [comment]
Should this be merged, has the babel plugin already been merged?

I think that maven is not a strict host requirement, because the Makefile pulls the official maven from Docker Hub if it is not already there, but docker, docker-compose, make and git are all requirements on the host machine if you're making a local build, for sure. 

With the current dev branch I was able to build and launch services on a Linux host, one service didn't start up properly and I have logged this as a separate issue.

**Comment by mikkohei13** [comment]
I believe these settings are already outdated for the current dev branch. Should create new instructions for running everything in Docker instead, including Ember?

**Comment by mskyttner** [comment]
Ingimar reported that "make build-ui" breaks on current development branch on the new test server. @mikkohei13 - your suggested change seems to fix the build issue. So, I will now update the development branch with the changes I did. Also update the README.md there with more deployment instruction details.

**Comment by mskyttner** [comment]
The development branch should now adress the issues mentioned in this PR, see the latest commits on that branch, for example: 6fd61160c8925d3a0bd467dfcbdec3b4dbbe8885

**Comment by mikkohei13** [comment]
Fixed by #6fd61160c8925d3a0bd467dfcbdec3b4dbbe8885

**Comment by mskyttner** [comment]
@mikkohei13  should the branch be removed?

**Pull request closed without merging**
